#!/bin/sh -eu

MASTER=${1:-./dist/build/master/master}
DIR=$(dirname $0)

$MASTER -v
$MASTER --version
$MASTER list

MASTER="$MASTER --dry-run"

for f in $(ls $DIR/examples/pass); do
  f="${DIR}/examples/pass/${f}"
  if echo "${f}" | grep -v "no-default"; then
    $MASTER build -f ${f}
  fi
  if echo "${f}" | grep -v "no-builds"; then
    $MASTER build -f ${f} "one"
  fi
  if $MASTER build -f ${f} "badbuild"; then exit 1; fi
done

for f in $(ls $DIR/examples/fail); do
  f="${DIR}/examples/fail/${f}"
  if $MASTER build -f ${f}; then
    echo "No error when running ${f}"
    exit 1
  fi
done
